---
# Source: prometheus/templates/configmaps/alertmanager.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: RELEASE-NAME
    chart: prometheus-11.12.0
    heritage: Helm
  name: RELEASE-NAME-prometheus-alertmanager
  namespace: NAMESPACE
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: default-receiver
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h
