---
# Source: prometheus/templates/persistentvolumeclaims/server.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
  labels:
    component: "server"
    app: prometheus
    release: RELEASE-NAME
    chart: prometheus-11.12.0
    heritage: Helm
  name: RELEASE-NAME-prometheus-server
  namespace: NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2Gi"
  storageClassName: gp2