---
# Source: prometheus/templates/rbac/alertmanager-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: RELEASE-NAME
    chart: prometheus-11.12.0
    heritage: Helm
  name: RELEASE-NAME-prometheus-alertmanager
  namespace: NAMESPACE
rules:
  []
