---
# Source: prometheus/templates/rbac/pushgateway-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "pushgateway"
    app: prometheus
    release: RELEASE-NAME
    chart: prometheus-11.12.0
    heritage: Helm
  name: RELEASE-NAME-prometheus-pushgateway
  namespace: NAMESPACE
  annotations:
    {}
