---
# Source: grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: RELEASE-NAME-grafana
  namespace: NAMESPACE
  labels:
    helm.sh/chart: grafana-5.5.5
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "7.1.1"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "UFZKU3VoaGFreE9oT29mWUFabjRKYVM2UERhSjZWZmpJVFFUWld6Zg=="
  ldap-toml: ""
